/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CompoundDetailsDialog.java
 *
 * Created on 19 Ιουλ 2010, 6:42:54 μμ
 */
package qedit;

import java.awt.Frame;
import javax.swing.DefaultListModel;
import qedit.clients.components.Compound;

/**
 *
 * @author hampos
 */
public class CompoundDetailsDialog extends javax.swing.JDialog {

    public static final int SGN_CLOSE = 0;
    public static final int SGN_APPLY_AND_CLOSE = 1;
    private int outputSignal = SGN_CLOSE;
    private Compound compound;
    private ReportInternalFrame rif;

    public ReportInternalFrame getRif() {
        return rif;
    }

    public void setRif(ReportInternalFrame rif) {
        this.rif = rif;
    }

    public int getCloseSignal() {
        return outputSignal;
    }

    protected void sendCloseSignal(int closeSignal) {
        this.outputSignal = closeSignal;
    }

    /** Creates new form CompoundDetailsDialog */
    public CompoundDetailsDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public CompoundDetailsDialog(Frame owner, Compound compound) {
        super(owner);
        this.compound = compound;
        initComponents();
    }

    public Compound getCompound() {
        return compound;
    }

    public void setCompound(Compound compound) {
        this.compound = compound;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        conformersList = new javax.swing.JList();
        chemicalNameField = new javax.swing.JTextField();
        casRnField = new javax.swing.JTextField();
        inChlField = new javax.swing.JTextField();
        smilesField = new javax.swing.JTextField();
        uriField = new javax.swing.JTextField();
        einecsField = new javax.swing.JTextField();
        reachRegDateField = new javax.swing.JTextField();
        closeButton = new javax.swing.JButton();
        inchiKeyField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        updateCompoundAndCloseButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(qedit.QEditApp.class).getContext().getResourceMap(CompoundDetailsDialog.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel1.border.title"))); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N

        jLabel1.setIcon(resourceMap.getIcon("jLabel1.icon")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N

        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        conformersList.setModel(new javax.swing.DefaultListModel());
        conformersList.setName("conformersList"); // NOI18N
        for(String conformer : compound.getConformers()){
            ((DefaultListModel) conformersList.getModel()).addElement(conformer);
        }
        jScrollPane1.setViewportView(conformersList);

        chemicalNameField.setText(resourceMap.getString("chemicalNameField.text")); // NOI18N
        chemicalNameField.setName("chemicalNameField"); // NOI18N
        chemicalNameField.setText(compound.getChemicalName());

        casRnField.setText(resourceMap.getString("casRnField.text")); // NOI18N
        casRnField.setName("casRnField"); // NOI18N
        casRnField.setText(compound.getCasRn());

        inChlField.setText(resourceMap.getString("inChlField.text")); // NOI18N
        inChlField.setName("inChlField"); // NOI18N
        inChlField.setText(compound.getInChI());

        smilesField.setText(resourceMap.getString("smilesField.text")); // NOI18N
        smilesField.setName("smilesField"); // NOI18N
        smilesField.setText(compound.getSmiles());

        uriField.setForeground(resourceMap.getColor("uriField.foreground")); // NOI18N
        uriField.setText(resourceMap.getString("uriField.text")); // NOI18N
        uriField.setName("uriField"); // NOI18N
        uriField.setText(compound.getUri());

        einecsField.setText(resourceMap.getString("einecsField.text")); // NOI18N
        einecsField.setName("einecsField"); // NOI18N
        einecsField.setText(compound.getEinecs());

        reachRegDateField.setText(resourceMap.getString("reachRegDateField.text")); // NOI18N
        reachRegDateField.setName("reachRegDateField"); // NOI18N
        reachRegDateField.setText(compound.getREACHRegistrationDate());

        closeButton.setIcon(resourceMap.getIcon("closeButton.icon")); // NOI18N
        closeButton.setText(resourceMap.getString("closeButton.text")); // NOI18N
        closeButton.setName("closeButton"); // NOI18N
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        inchiKeyField.setText(resourceMap.getString("inchiKeyField.text")); // NOI18N
        inchiKeyField.setName("inchiKeyField"); // NOI18N
        inchiKeyField.setText(compound.getInChIKey());

        jLabel9.setText(resourceMap.getString("jLabel9.text")); // NOI18N
        jLabel9.setName("jLabel9"); // NOI18N

        updateCompoundAndCloseButton.setIcon(resourceMap.getIcon("updateCompoundAndCloseButton.icon")); // NOI18N
        updateCompoundAndCloseButton.setText(resourceMap.getString("updateCompoundAndCloseButton.text")); // NOI18N
        updateCompoundAndCloseButton.setName("updateCompoundAndCloseButton"); // NOI18N
        updateCompoundAndCloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateCompoundAndCloseButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                        .add(closeButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(updateCompoundAndCloseButton))
                    .add(jLabel8)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(9, 9, 9)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(jLabel6)
                                    .add(jLabel5)
                                    .add(jLabel4)
                                    .add(jLabel9)
                                    .add(jLabel3)
                                    .add(jLabel2)
                                    .add(jLabel1)))
                            .add(jLabel7))
                        .add(18, 18, 18)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(reachRegDateField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                            .add(einecsField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                            .add(chemicalNameField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                            .add(casRnField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                            .add(inchiKeyField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                            .add(inChlField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                            .add(smilesField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                            .add(uriField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(20, 20, 20)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(uriField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel1))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(smilesField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel2))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(inChlField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel3))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(inchiKeyField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel9))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(casRnField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel4))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(chemicalNameField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel5))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(einecsField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel6))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(reachRegDateField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel7))
                .add(29, 29, 29)
                .add(jLabel8)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(updateCompoundAndCloseButton)
                    .add(closeButton))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        sendCloseSignal(SGN_CLOSE);
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void updateCompoundAndCloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateCompoundAndCloseButtonActionPerformed
        sendCloseSignal(SGN_APPLY_AND_CLOSE);
        compound.setCasRn(casRnField.getText());
        compound.setChemicalName(chemicalNameField.getText());
        compound.setEINECS(einecsField.getText());
        compound.setInChI(inChlField.getText());
        compound.setInChIKey(inchiKeyField.getText());
        compound.setREACHRegistrationDate(reachRegDateField.getText());
        compound.setUri(uriField.getText());
        compound.setSmiles(smilesField.getText());
        setVisible(false);
        dispose();
        rif.synchronizeCompoundFieldsWRTReport();
    }//GEN-LAST:event_updateCompoundAndCloseButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                CompoundDetailsDialog dialog = new CompoundDetailsDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField casRnField;
    private javax.swing.JTextField chemicalNameField;
    private javax.swing.JButton closeButton;
    private javax.swing.JList conformersList;
    private javax.swing.JTextField einecsField;
    private javax.swing.JTextField inChlField;
    private javax.swing.JTextField inchiKeyField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField reachRegDateField;
    private javax.swing.JTextField smilesField;
    private javax.swing.JButton updateCompoundAndCloseButton;
    private javax.swing.JTextField uriField;
    // End of variables declaration//GEN-END:variables
}
