/*
 * EditorOptionsDialog.java
 *
 * Created on 9 Ιουλ 2010, 8:08:29 μμ
 */
package qedit;

import java.awt.Color;
import java.awt.Frame;
import java.awt.Image;
import java.util.LinkedHashMap;
import java.util.Map;

/**
 *
 * @author hampos
 */
public class EditorOptionsDialog extends javax.swing.JDialog {

    private static Map<String, String> imageServiceComboOptions = new java.util.LinkedHashMap<String, String>();
    static {
      imageServiceComboOptions.put("AMBIT Cactvs", QEditApp.ambit_cactvs_imageService);
      imageServiceComboOptions.put("AMBIT CDK", QEditApp.ambit_cdk_imageService);
      imageServiceComboOptions.put("AMBIT Daylight", QEditApp.ambit_daylight_imageService);
      imageServiceComboOptions.put("Idea Cactvs", QEditApp.ideaconsult_cactvs_imageService);
      imageServiceComboOptions.put("Idea CDK", QEditApp.ideaconsult_cdk_imageService);
      imageServiceComboOptions.put("Idea Daylight", QEditApp.ideaconsult_daylight_imageService);
    };
    private static Map<String, Integer> magnificationAlgorithm = new java.util.LinkedHashMap<String, Integer>();
    static {
        magnificationAlgorithm.put("Default", Image.SCALE_DEFAULT);
        magnificationAlgorithm.put("Area Averaging", Image.SCALE_AREA_AVERAGING);
        magnificationAlgorithm.put("Fast", Image.SCALE_FAST);
        magnificationAlgorithm.put("Replicate", Image.SCALE_REPLICATE);
        magnificationAlgorithm.put("Smooth", Image.SCALE_SMOOTH);
    }

    /** Creates new form EditorOptionsDialog */
    public EditorOptionsDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public EditorOptionsDialog(Frame owner) {
        super(owner);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        imageServiceButtonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        cancelButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();
        tabbedPanel = new javax.swing.JTabbedPane();
        imageServicePanel = new javax.swing.JPanel();
        imageServiceHeaderLabel = new javax.swing.JLabel();
        chooseImageServiceRadio = new javax.swing.JRadioButton();
        customImageServiceRadio = new javax.swing.JRadioButton();
        imageServiceCombo = new javax.swing.JComboBox();
        imageServiceField = new javax.swing.JTextField();
        imageServiceHintLamp = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        magnificationModeSelectorCombbo = new javax.swing.JComboBox();
        compoundServicePanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        casToSmilesServiceTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        smilesToUriServiceTextField = new javax.swing.JTextField();
        modelServicePanel = new javax.swing.JPanel();
        algorithmServicePanel = new javax.swing.JPanel();
        ontologyServicePanel = new javax.swing.JPanel();
        pdfOptionsPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(qedit.QEditApp.class).getContext().getResourceMap(EditorOptionsDialog.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N

        cancelButton.setIcon(resourceMap.getIcon("cancelButton.icon")); // NOI18N
        cancelButton.setText(resourceMap.getString("cancelButton.text")); // NOI18N
        cancelButton.setName("cancelButton"); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        okButton.setIcon(resourceMap.getIcon("okButton.icon")); // NOI18N
        okButton.setText(resourceMap.getString("okButton.text")); // NOI18N
        okButton.setToolTipText(resourceMap.getString("okButton.toolTipText")); // NOI18N
        okButton.setName("okButton"); // NOI18N
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        tabbedPanel.setName("tabbedPanel"); // NOI18N

        imageServicePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("imageServicePanel.border.title"))); // NOI18N
        imageServicePanel.setName("imageServicePanel"); // NOI18N

        imageServiceHeaderLabel.setFont(resourceMap.getFont("imageServiceHeaderLabel.font")); // NOI18N
        imageServiceHeaderLabel.setText(resourceMap.getString("imageServiceHeaderLabel.text")); // NOI18N
        imageServiceHeaderLabel.setName("imageServiceHeaderLabel"); // NOI18N

        imageServiceButtonGroup.add(chooseImageServiceRadio);
        chooseImageServiceRadio.setSelected(true);
        chooseImageServiceRadio.setText(resourceMap.getString("chooseImageServiceRadio.text")); // NOI18N
        chooseImageServiceRadio.setName("chooseImageServiceRadio"); // NOI18N

        imageServiceButtonGroup.add(customImageServiceRadio);
        customImageServiceRadio.setText(resourceMap.getString("customImageServiceRadio.text")); // NOI18N
        customImageServiceRadio.setName("customImageServiceRadio"); // NOI18N

        String[] availableImageServices = imageServiceComboOptions.keySet().toArray(new String[]{});
        imageServiceCombo.setModel(new javax.swing.DefaultComboBoxModel(availableImageServices));
        imageServiceCombo.setToolTipText(resourceMap.getString("imageServiceCombo.toolTipText")); // NOI18N
        imageServiceCombo.setName("imageServiceCombo"); // NOI18N

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, chooseImageServiceRadio, org.jdesktop.beansbinding.ELProperty.create("${selected}"), imageServiceCombo, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        imageServiceCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                imageServiceComboItemStateChanged(evt);
            }
        });

        imageServiceField.setForeground(resourceMap.getColor("imageServiceField.foreground")); // NOI18N
        imageServiceField.setText(resourceMap.getString("imageServiceField.text")); // NOI18N
        imageServiceField.setName("imageServiceField"); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, customImageServiceRadio, org.jdesktop.beansbinding.ELProperty.create("${selected}"), imageServiceField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        imageServiceHintLamp.setIcon(resourceMap.getIcon("imageServiceHintLamp.icon")); // NOI18N
        imageServiceHintLamp.setText(resourceMap.getString("imageServiceHintLamp.text")); // NOI18N
        imageServiceHintLamp.setName("imageServiceHintLamp"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        String[] availableMagnificationAlgorithms = magnificationAlgorithm.keySet().toArray(new String[]{});
        magnificationModeSelectorCombbo.setModel(new javax.swing.DefaultComboBoxModel(availableMagnificationAlgorithms));
        magnificationModeSelectorCombbo.setToolTipText(resourceMap.getString("magnificationModeSelectorCombbo.toolTipText")); // NOI18N
        magnificationModeSelectorCombbo.setName("magnificationModeSelectorCombbo"); // NOI18N

        org.jdesktop.layout.GroupLayout imageServicePanelLayout = new org.jdesktop.layout.GroupLayout(imageServicePanel);
        imageServicePanel.setLayout(imageServicePanelLayout);
        imageServicePanelLayout.setHorizontalGroup(
            imageServicePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(imageServicePanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(imageServicePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(imageServiceCombo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 252, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(imageServiceHeaderLabel)
                    .add(imageServicePanelLayout.createSequentialGroup()
                        .add(chooseImageServiceRadio)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(imageServiceHintLamp))
                    .add(customImageServiceRadio)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, imageServiceField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
                    .add(imageServicePanelLayout.createSequentialGroup()
                        .add(jLabel2)
                        .add(18, 18, 18)
                        .add(magnificationModeSelectorCombbo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 146, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        imageServicePanelLayout.setVerticalGroup(
            imageServicePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(imageServicePanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(imageServiceHeaderLabel)
                .add(18, 18, 18)
                .add(imageServicePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(chooseImageServiceRadio)
                    .add(imageServiceHintLamp))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(imageServiceCombo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(customImageServiceRadio)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(imageServiceField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 36, Short.MAX_VALUE)
                .add(imageServicePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(magnificationModeSelectorCombbo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tabbedPanel.addTab(resourceMap.getString("imageServicePanel.TabConstraints.tabTitle"), imageServicePanel); // NOI18N

        compoundServicePanel.setName("compoundServicePanel"); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel2.border.title"))); // NOI18N
        jPanel2.setName("jPanel2"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        casToSmilesServiceTextField.setForeground(resourceMap.getColor("jTextField1.foreground")); // NOI18N
        casToSmilesServiceTextField.setText(resourceMap.getString("casToSmilesServiceTextField.text")); // NOI18N
        casToSmilesServiceTextField.setToolTipText(resourceMap.getString("casToSmilesServiceTextField.toolTipText")); // NOI18N
        casToSmilesServiceTextField.setName("casToSmilesServiceTextField"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        smilesToUriServiceTextField.setForeground(resourceMap.getColor("smilesToUriServiceTextField.foreground")); // NOI18N
        smilesToUriServiceTextField.setText(resourceMap.getString("smilesToUriServiceTextField.text")); // NOI18N
        smilesToUriServiceTextField.setName("smilesToUriServiceTextField"); // NOI18N

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jLabel3)
                    .add(jLabel1))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(smilesToUriServiceTextField)
                    .add(casToSmilesServiceTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(casToSmilesServiceTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(smilesToUriServiceTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout compoundServicePanelLayout = new org.jdesktop.layout.GroupLayout(compoundServicePanel);
        compoundServicePanel.setLayout(compoundServicePanelLayout);
        compoundServicePanelLayout.setHorizontalGroup(
            compoundServicePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(compoundServicePanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        compoundServicePanelLayout.setVerticalGroup(
            compoundServicePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(compoundServicePanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(124, Short.MAX_VALUE))
        );

        tabbedPanel.addTab(resourceMap.getString("compoundServicePanel.TabConstraints.tabTitle"), compoundServicePanel); // NOI18N

        modelServicePanel.setName("modelServicePanel"); // NOI18N

        org.jdesktop.layout.GroupLayout modelServicePanelLayout = new org.jdesktop.layout.GroupLayout(modelServicePanel);
        modelServicePanel.setLayout(modelServicePanelLayout);
        modelServicePanelLayout.setHorizontalGroup(
            modelServicePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 646, Short.MAX_VALUE)
        );
        modelServicePanelLayout.setVerticalGroup(
            modelServicePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 283, Short.MAX_VALUE)
        );

        tabbedPanel.addTab(resourceMap.getString("modelServicePanel.TabConstraints.tabTitle"), modelServicePanel); // NOI18N

        algorithmServicePanel.setName("algorithmServicePanel"); // NOI18N

        org.jdesktop.layout.GroupLayout algorithmServicePanelLayout = new org.jdesktop.layout.GroupLayout(algorithmServicePanel);
        algorithmServicePanel.setLayout(algorithmServicePanelLayout);
        algorithmServicePanelLayout.setHorizontalGroup(
            algorithmServicePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 646, Short.MAX_VALUE)
        );
        algorithmServicePanelLayout.setVerticalGroup(
            algorithmServicePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 283, Short.MAX_VALUE)
        );

        tabbedPanel.addTab(resourceMap.getString("algorithmServicePanel.TabConstraints.tabTitle"), algorithmServicePanel); // NOI18N

        ontologyServicePanel.setName("ontologyServicePanel"); // NOI18N

        org.jdesktop.layout.GroupLayout ontologyServicePanelLayout = new org.jdesktop.layout.GroupLayout(ontologyServicePanel);
        ontologyServicePanel.setLayout(ontologyServicePanelLayout);
        ontologyServicePanelLayout.setHorizontalGroup(
            ontologyServicePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 646, Short.MAX_VALUE)
        );
        ontologyServicePanelLayout.setVerticalGroup(
            ontologyServicePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 283, Short.MAX_VALUE)
        );

        tabbedPanel.addTab(resourceMap.getString("ontologyServicePanel.TabConstraints.tabTitle"), ontologyServicePanel); // NOI18N

        pdfOptionsPanel.setName("pdfOptionsPanel"); // NOI18N

        org.jdesktop.layout.GroupLayout pdfOptionsPanelLayout = new org.jdesktop.layout.GroupLayout(pdfOptionsPanel);
        pdfOptionsPanel.setLayout(pdfOptionsPanelLayout);
        pdfOptionsPanelLayout.setHorizontalGroup(
            pdfOptionsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 646, Short.MAX_VALUE)
        );
        pdfOptionsPanelLayout.setVerticalGroup(
            pdfOptionsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 283, Short.MAX_VALUE)
        );

        tabbedPanel.addTab(resourceMap.getString("pdfOptionsPanel.TabConstraints.tabTitle"), pdfOptionsPanel); // NOI18N

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(457, Short.MAX_VALUE)
                .add(cancelButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(okButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(org.jdesktop.layout.GroupLayout.TRAILING, tabbedPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(374, Short.MAX_VALUE)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(okButton)
                    .add(cancelButton)))
            .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(jPanel1Layout.createSequentialGroup()
                    .add(tabbedPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 339, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(64, Short.MAX_VALUE)))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        casToSmilesServiceTextField.setBackground(Color.white);
        if (chooseImageServiceRadio.isSelected()) {
                QEditApp.setImageService(imageServiceComboOptions.
                        get(imageServiceCombo.getSelectedItem().toString()));
        } else {
            QEditApp.setImageService(imageServiceField.getText());
        }
        if (casToSmilesServiceTextField.getText().isEmpty()) {
            tabbedPanel.setSelectedComponent(compoundServicePanel);
            casToSmilesServiceTextField.setBackground(Color.yellow);
            return;
        }
        QEditApp.setMagnificationMode(magnificationAlgorithm.get(magnificationModeSelectorCombbo.getSelectedItem().toString()));
        QEditApp.setCasToSmilesService(casToSmilesServiceTextField.getText());
        QEditApp.setSmilesToUriService(smilesToUriServiceTextField.getText());
        dispose();
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void imageServiceComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_imageServiceComboItemStateChanged
        imageServiceField.setText(imageServiceComboOptions.get(imageServiceCombo.getSelectedItem().toString()));
    }//GEN-LAST:event_imageServiceComboItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                EditorOptionsDialog dialog = new EditorOptionsDialog(new javax.swing.JFrame(), true){

                    @Override
                    public void dispose() {
                        super.dispose();
                        System.exit(0);
                    }

                };
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel algorithmServicePanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField casToSmilesServiceTextField;
    private javax.swing.JRadioButton chooseImageServiceRadio;
    private javax.swing.JPanel compoundServicePanel;
    private javax.swing.JRadioButton customImageServiceRadio;
    private javax.swing.ButtonGroup imageServiceButtonGroup;
    private javax.swing.JComboBox imageServiceCombo;
    private javax.swing.JTextField imageServiceField;
    private javax.swing.JLabel imageServiceHeaderLabel;
    private javax.swing.JLabel imageServiceHintLamp;
    private javax.swing.JPanel imageServicePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox magnificationModeSelectorCombbo;
    private javax.swing.JPanel modelServicePanel;
    private javax.swing.JButton okButton;
    private javax.swing.JPanel ontologyServicePanel;
    private javax.swing.JPanel pdfOptionsPanel;
    private javax.swing.JTextField smilesToUriServiceTextField;
    private javax.swing.JTabbedPane tabbedPanel;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
