/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EnterUriDialog.java
 *
 * Created on Jun 5, 2010, 5:55:23 AM
 */

package qedit;

import java.awt.Color;

/**
 *
 * @author chung
 */
public class EnterUriDialog extends javax.swing.JDialog {

     public EnterUriDialog(java.awt.Frame parent) {
        super(parent);
        initComponents();
    }

    /** Creates new form EnterUriDialog */
    public EnterUriDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        datasetUriLabel = new javax.swing.JLabel();
        datasetUriValue = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        datasetUriExplanation = new javax.swing.JLabel();
        modelUriExplanation = new javax.swing.JLabel();
        modelUriValue = new javax.swing.JTextField();
        loadFromRemoteButton = new javax.swing.JButton();
        requireCredentials = new java.awt.Checkbox();
        userPasswordValue = new javax.swing.JPasswordField();
        userNameVariable = new javax.swing.JTextField();
        cancellationButton = new javax.swing.JButton();
        provideCredentialsHint = new javax.swing.JLabel();
        passwordQuality = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(qedit.QEditApp.class).getContext().getResourceMap(EnterUriDialog.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N

        datasetUriLabel.setFont(resourceMap.getFont("datasetUriLabel.font")); // NOI18N
        datasetUriLabel.setText(resourceMap.getString("datasetUriLabel.text")); // NOI18N
        datasetUriLabel.setName("datasetUriLabel"); // NOI18N

        datasetUriValue.setText(resourceMap.getString("datasetUriValue.text")); // NOI18N
        datasetUriValue.setName("datasetUriValue"); // NOI18N
        datasetUriValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datasetUriValueActionPerformed(evt);
            }
        });

        jLabel3.setFont(resourceMap.getFont("jLabel3.font")); // NOI18N
        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        datasetUriExplanation.setText(resourceMap.getString("datasetUriExplanation.text")); // NOI18N
        datasetUriExplanation.setName("datasetUriExplanation"); // NOI18N

        modelUriExplanation.setText(resourceMap.getString("modelUriExplanation.text")); // NOI18N
        modelUriExplanation.setName("modelUriExplanation"); // NOI18N

        modelUriValue.setText(resourceMap.getString("modelUriValue.text")); // NOI18N
        modelUriValue.setName("modelUriValue"); // NOI18N

        loadFromRemoteButton.setText(resourceMap.getString("loadFromRemoteButton.text")); // NOI18N
        loadFromRemoteButton.setName("loadFromRemoteButton"); // NOI18N

        requireCredentials.setLabel(resourceMap.getString("requireCredentials.label")); // NOI18N
        requireCredentials.setName("requireCredentials"); // NOI18N

        userPasswordValue.setForeground(resourceMap.getColor("userPasswordValue.foreground")); // NOI18N
        userPasswordValue.setText(resourceMap.getString("userPasswordValue.text")); // NOI18N
        userPasswordValue.setName("userPasswordValue"); // NOI18N
        userPasswordValue.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                userPasswordValueCaretUpdate(evt);
            }
        });

        userNameVariable.setText(resourceMap.getString("userNameVariable.text")); // NOI18N
        userNameVariable.setName("userNameVariable"); // NOI18N
        userNameVariable.setEnabled(false);

        cancellationButton.setText(resourceMap.getString("cancellationButton.text")); // NOI18N
        cancellationButton.setName("cancellationButton"); // NOI18N

        provideCredentialsHint.setText(resourceMap.getString("provideCredentialsHint.text")); // NOI18N
        provideCredentialsHint.setName("provideCredentialsHint"); // NOI18N

        passwordQuality.setText(resourceMap.getString("passwordQuality.text")); // NOI18N
        passwordQuality.setName("passwordQuality"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cancellationButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(loadFromRemoteButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(requireCredentials, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel3)
                            .addComponent(datasetUriLabel))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(datasetUriExplanation)
                            .addComponent(datasetUriValue, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                            .addComponent(modelUriValue, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(userNameVariable, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(userPasswordValue, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(passwordQuality))
                            .addComponent(modelUriExplanation, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(provideCredentialsHint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(217, 217, 217)))))
                .addGap(82, 82, 82))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(datasetUriValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(datasetUriLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(datasetUriExplanation)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(modelUriValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modelUriExplanation)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(userNameVariable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userPasswordValue)
                            .addComponent(passwordQuality))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(provideCredentialsHint, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE)
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(loadFromRemoteButton)
                            .addComponent(cancellationButton)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(requireCredentials, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(75, 75, 75)))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void datasetUriValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datasetUriValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_datasetUriValueActionPerformed

    private void userPasswordValueCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_userPasswordValueCaretUpdate
        int passLength = userPasswordValue.getPassword().length;
        if (passLength<=4){
            userPasswordValue.setForeground(Color.CYAN);
            passwordQuality.setText("LOW");
        } else if (passLength>=5 && passLength<=8){
            userPasswordValue.setForeground(Color.GREEN);
            passwordQuality.setText("MED");
        }else if (passLength>=9 & passLength <= 12){
            userPasswordValue.setForeground(Color.ORANGE);
            passwordQuality.setText("GOOD");
        }else if (passLength>=13){
            userPasswordValue.setForeground(Color.RED);
            passwordQuality.setText("HIGH");
        }
        
    }//GEN-LAST:event_userPasswordValueCaretUpdate
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancellationButton;
    private javax.swing.JLabel datasetUriExplanation;
    private javax.swing.JLabel datasetUriLabel;
    private javax.swing.JTextField datasetUriValue;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loadFromRemoteButton;
    private javax.swing.JLabel modelUriExplanation;
    private javax.swing.JTextField modelUriValue;
    private javax.swing.JLabel passwordQuality;
    private javax.swing.JLabel provideCredentialsHint;
    private java.awt.Checkbox requireCredentials;
    private javax.swing.JTextField userNameVariable;
    private javax.swing.JPasswordField userPasswordValue;
    // End of variables declaration//GEN-END:variables

}
