/*
 * MagnifiedImage.java
 *
 * Created on Jul 11, 2010, 3:41:06 AM
 */
package qedit;

import java.awt.Frame;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import org.jdesktop.application.ApplicationContext;
import org.jdesktop.application.Task;
import org.jdesktop.application.TaskMonitor;
import org.jdesktop.application.TaskService;

/**
 *
 * @author chung
 */
public class MagnifiedImage extends javax.swing.JDialog {

    private ImageIcon icon;

    /** Creates new form MagnifiedImage */
    public MagnifiedImage(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public MagnifiedImage(Frame owner) {
        super(owner);
        initComponents();
    }

    public void setIcon(ImageIcon icon) {
        getImageLabel().setIcon(icon);
        this.icon = icon;
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        zoomCompoundButton = new javax.swing.JButton();
        unzoomCompoundButton = new javax.swing.JButton();
        resetSizeButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        imageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(qedit.QEditApp.class).getContext().getResourceMap(MagnifiedImage.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setName("jPanel2"); // NOI18N

        jPanel3.setName("jPanel3"); // NOI18N

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        jToolBar1.setName("jToolBar1"); // NOI18N

        zoomCompoundButton.setIcon(resourceMap.getIcon("zoomCompoundButton.icon")); // NOI18N
        zoomCompoundButton.setText(resourceMap.getString("zoomCompoundButton.text")); // NOI18N
        zoomCompoundButton.setFocusable(false);
        zoomCompoundButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        zoomCompoundButton.setName("zoomCompoundButton"); // NOI18N
        zoomCompoundButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        zoomCompoundButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zoomCompoundButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(zoomCompoundButton);

        unzoomCompoundButton.setIcon(resourceMap.getIcon("unzoomCompoundButton.icon")); // NOI18N
        unzoomCompoundButton.setText(resourceMap.getString("unzoomCompoundButton.text")); // NOI18N
        unzoomCompoundButton.setFocusable(false);
        unzoomCompoundButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        unzoomCompoundButton.setName("unzoomCompoundButton"); // NOI18N
        unzoomCompoundButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        unzoomCompoundButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unzoomCompoundButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(unzoomCompoundButton);

        resetSizeButton.setIcon(resourceMap.getIcon("resetSizeButton.icon")); // NOI18N
        resetSizeButton.setText(resourceMap.getString("resetSizeButton.text")); // NOI18N
        resetSizeButton.setFocusable(false);
        resetSizeButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        resetSizeButton.setName("resetSizeButton"); // NOI18N
        resetSizeButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        resetSizeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetSizeButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(resetSizeButton);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N

        imageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imageLabel.setText(resourceMap.getString("imageLabel.text")); // NOI18N
        imageLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        imageLabel.setName("imageLabel"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(imageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void zoom(final double scalingFactor){
        Task zoomTask = new Task(QEditApp.getApplication()) {

            @Override
            protected Object doInBackground() throws Exception {
                int newWidth = (int) Math.round((double)imageLabel.getIcon().getIconWidth() * scalingFactor);
                int newHeight = (int) Math.round((double)imageLabel.getIcon().getIconHeight()* scalingFactor);
                imageLabel.setIcon(new ImageIcon(((ImageIcon) imageLabel.getIcon()).getImage().
                        getScaledInstance(newWidth, newHeight, Image.SCALE_AREA_AVERAGING)));
                imageLabel.setSize(newWidth, newHeight);
                return new Object();
            }
        };
        ApplicationContext appC = QEditApp.getInstance().getContext();
        TaskMonitor taskMonitor = appC.getTaskMonitor();
        TaskService taskService = appC.getTaskService();
        taskService.execute(zoomTask);
        taskMonitor.setForegroundTask(zoomTask);
    }

    private void zoomCompoundButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zoomCompoundButtonActionPerformed
        zoom(1.4);
    }//GEN-LAST:event_zoomCompoundButtonActionPerformed

    private void unzoomCompoundButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unzoomCompoundButtonActionPerformed
        zoom(1/1.4);
    }//GEN-LAST:event_unzoomCompoundButtonActionPerformed

    private void resetSizeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetSizeButtonActionPerformed
        imageLabel.setIcon(icon);
    }//GEN-LAST:event_resetSizeButtonActionPerformed

    public JLabel getImageLabel() {
        return imageLabel;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imageLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton resetSizeButton;
    private javax.swing.JButton unzoomCompoundButton;
    private javax.swing.JButton zoomCompoundButton;
    // End of variables declaration//GEN-END:variables
}
