/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ReportInternalFrame.java
 *
 * Created on Jun 7, 2010, 9:47:54 AM
 */

package qedit;

/**
 *
 * @author chung
 */
public class ReportInternalFrame extends javax.swing.JInternalFrame {

    /** Creates new form ReportInternalFrame */
    public ReportInternalFrame() {
        initComponents();
        revalidate();
        repaint();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        basicTabbedPanel = new javax.swing.JTabbedPane();
        modelPanel = new javax.swing.JPanel();
        datasetPanel = new javax.swing.JPanel();
        qprfReport = new javax.swing.JPanel();
        qprfInfoTabbedSubPanel = new javax.swing.JTabbedPane();
        authors = new javax.swing.JPanel();
        bibtex = new javax.swing.JPanel();
        other = new javax.swing.JPanel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(qedit.QEditApp.class).getContext().getResourceMap(ReportInternalFrame.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setFrameIcon(resourceMap.getIcon("Form.frameIcon")); // NOI18N
        setName("Form"); // NOI18N

        basicTabbedPanel.setName("basicTabbedPanel"); // NOI18N

        modelPanel.setName("modelPanel"); // NOI18N

        javax.swing.GroupLayout modelPanelLayout = new javax.swing.GroupLayout(modelPanel);
        modelPanel.setLayout(modelPanelLayout);
        modelPanelLayout.setHorizontalGroup(
            modelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );
        modelPanelLayout.setVerticalGroup(
            modelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 273, Short.MAX_VALUE)
        );

        basicTabbedPanel.addTab(resourceMap.getString("modelPanel.TabConstraints.tabTitle"), null, modelPanel); // NOI18N

        datasetPanel.setName("datasetPanel"); // NOI18N

        javax.swing.GroupLayout datasetPanelLayout = new javax.swing.GroupLayout(datasetPanel);
        datasetPanel.setLayout(datasetPanelLayout);
        datasetPanelLayout.setHorizontalGroup(
            datasetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );
        datasetPanelLayout.setVerticalGroup(
            datasetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 273, Short.MAX_VALUE)
        );

        basicTabbedPanel.addTab(resourceMap.getString("datasetPanel.TabConstraints.tabTitle"), null, datasetPanel); // NOI18N

        qprfReport.setName("qprfReport"); // NOI18N

        qprfInfoTabbedSubPanel.setName("qprfInfoTabbedSubPanel"); // NOI18N

        authors.setName("authors"); // NOI18N

        javax.swing.GroupLayout authorsLayout = new javax.swing.GroupLayout(authors);
        authors.setLayout(authorsLayout);
        authorsLayout.setHorizontalGroup(
            authorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 406, Short.MAX_VALUE)
        );
        authorsLayout.setVerticalGroup(
            authorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 242, Short.MAX_VALUE)
        );

        qprfInfoTabbedSubPanel.addTab("Authors", authors);

        bibtex.setName("bibtex"); // NOI18N

        javax.swing.GroupLayout bibtexLayout = new javax.swing.GroupLayout(bibtex);
        bibtex.setLayout(bibtexLayout);
        bibtexLayout.setHorizontalGroup(
            bibtexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 406, Short.MAX_VALUE)
        );
        bibtexLayout.setVerticalGroup(
            bibtexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 242, Short.MAX_VALUE)
        );

        qprfInfoTabbedSubPanel.addTab("BibTex", bibtex);

        other.setName("other"); // NOI18N

        javax.swing.GroupLayout otherLayout = new javax.swing.GroupLayout(other);
        other.setLayout(otherLayout);
        otherLayout.setHorizontalGroup(
            otherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 406, Short.MAX_VALUE)
        );
        otherLayout.setVerticalGroup(
            otherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 242, Short.MAX_VALUE)
        );

        qprfInfoTabbedSubPanel.addTab("Other", other);

        javax.swing.GroupLayout qprfReportLayout = new javax.swing.GroupLayout(qprfReport);
        qprfReport.setLayout(qprfReportLayout);
        qprfReportLayout.setHorizontalGroup(
            qprfReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(qprfInfoTabbedSubPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
        );
        qprfReportLayout.setVerticalGroup(
            qprfReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(qprfInfoTabbedSubPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
        );

        basicTabbedPanel.addTab(resourceMap.getString("qprfReport.TabConstraints.tabTitle"), null, qprfReport); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(basicTabbedPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(basicTabbedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel authors;
    private javax.swing.JTabbedPane basicTabbedPanel;
    private javax.swing.JPanel bibtex;
    private javax.swing.JPanel datasetPanel;
    private javax.swing.JPanel modelPanel;
    private javax.swing.JPanel other;
    private javax.swing.JTabbedPane qprfInfoTabbedSubPanel;
    private javax.swing.JPanel qprfReport;
    // End of variables declaration//GEN-END:variables

}
